# name: Node CI

# on: 
#   push:
#     branches: [ master ]
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v1
#     - name: Install Node.js
#       uses: actions/setup-node@v1
#       with:
#         node-version: '12.x'
#     - name: npm install and build
#       run: |
#         npm install
#         npm run build
#     - name: List output files
#       run: ls -a ./dist/
#     - name: parent working directory
#       run: pwd
#     - name: copy file via ssh password
#       uses: appleboy/scp-action@master
#       with:
#         host: ${{ secrets.REMOTE_HOST }}
#         username: ${{ secrets.REMOTE_USER }}
#         password: ${{ secrets.PASSWORD }}
#         port: 22
#         source: "./dist"
#         target: "/usr/wclDemo"