name: Node CI

on: 
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: npm install and build
      run: |
        npm install
        npm run build
    - name: List output files
      run: ls -a ./dist/
    - name: Deploy
      uses: garygrossgarten/github-action-scp@release
      with:
          local: ./dist/
          remote: /usr/wclDemo/vueDemo
          host: ${{ secrets.REMOTE_HOST }}
          port: 22
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.PASSWORD }}
          concurrency: 20
          recursive: true