name: Node CI

on: 
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build
    - name: List output files
      run: ls -a ./dist/ # 显示生成的目录文件
    - name: Deploy to Server
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: ${{ secrets.REMOTE_HOST }}
        ftp-username: ${{ secrets.REMOTE_USER }}
        ftp-password: ${{ secrets.PASSWORD }}
        local-dir: ./dist/
        git-ftp-args: --insecure --remote-root /usr/wclDemo/vueDemo # 要部署到服务器的哪个位置（如果是FTP连接的话--insecure不用加）（是SFTP链接的话不需要加？）